---
- name: yum update and install
  hosts: all
  become: yes
  tasks:
  - name: install htop with yum
    yum:
      name: htop
      state: latest
  - name: git update
    yum:
      name: git
      state: latest
  - name: install vim and mlocate
    yum:
      name:
        - vim
        - mlocate
      state: latest
   - name: update mlocate
     command: updatedb
