---
- name: Install vim, locate and htop
  hosts: all
  become: yes
  
  tasks:
  - name: run yum update
    yum:
      name: "*"
      state: latest
      skip_broken: yes
  - name: install vim locate and htop with yum  
    yum:
      name: {{ item }}
      state: latest
      with_items:
      - vim
      - mlocate
      - htop
