---
- name: Install vim, locate and htop
  hosts: localhost
  become: yes
  
  tasks:
  - name: install vim locate and htop with yum  
    yum: name={{ item }} state=present
    with_items:
    - vim
    - mlocate
    - htop
