---
- name: yum update and install
  hosts: all
  become: yes
  tasks:
  - name: install vim locate and htop with yum
    yum:
      name: htop
      state: latest
  - name: run yum repolist
    command: yum repolist
  - name: yum update
    yum:
      name: "*"
      state: latest
      skip_broken: yes
