---
- name: yum update and install
  hosts: all
  become: yes
  tasks:
  - name: install htop with yum
    yum:
      name: htop
      state: absent
  - name: git update
    yum:
      name: git
      state: absent
  - name: install vim and mlocate
    yum:
      name:
        - vim
        - mlocate
      state: absent
   - name: yum cleanup
     yum:
        autoremove: yes
   - name: update locate db
     shell: updatedb
   -name: run yum update
    shell: yum update --skip-broken -y
